# =====================================================
# APPLICATION
# =====================================================
spring.application.name=image-service
server.port=8081
server.address=0.0.0.0
spring.profiles.active=prod

# =====================================================
# DATABASE (POSTGRES)
# =====================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=image
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =====================================================
# LIQUIBASE
# =====================================================
spring.liquibase.enabled=true
spring.liquibase.default-schema=image
spring.liquibase.liquibase-schema=image
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

# =====================================================
# REDIS
# =====================================================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.timeout=60000
spring.cache.type=redis

# =====================================================
# GCP CONFIG
# =====================================================
spring.cloud.gcp.project-id=${GCP_PROJECT_ID}
spring.cloud.gcp.credentials.location=${GOOGLE_APPLICATION_CREDENTIALS}

# =====================================================
# GCS
# =====================================================
gcs.bucket.name=${GCS_BUCKET_NAME}
gcs.object.base-path=devices
gcs.signed-url.expiry-minutes=15

# =====================================================
# PUB/SUB
# =====================================================
spring.cloud.gcp.pubsub.enabled=true
pubsub.subscription.device-registered=${PUBSUB_DEVICE_REGISTERED}
pubsub.subscription.device-status-updated=${PUBSUB_STATUS_UPDATED}

# =====================================================
# EXTERNAL SERVICES
# =====================================================
device.service.url=${DEVICE_SERVICE_URL}
spring.devtools.restart.enabled=false
